functional:
 - Пользователь должен иметь возможность искать товары по ключевому слову или категории
 - Пользователь должен иметь возможность фильтровать товары
 - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
 - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
 - Пользователь должен иметь возможность переключить язык интерфейса
 - Сайт должен иметь локализацию (перевод) на русский и английский языки
non-functional:
 - Сайт должен быть безопасным и защищать данные пользователя
 - Важно, чтобы сайт мог обрабатывать большое количество трафика
 - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
 - Сайт нужно протестировать на совместимость с последними версиями браузеров
 - Сайт должен быть доступен на различных устройствах
 - Сайт должен иметь мобильную версию
implicit:
  - Пользователь должен иметь возможность оставлять и просматривать отзывы на товар
  - Пользователь должен иметь возможность регистрироваться и авторизироваться на сайте
  - Пользователь должен иметь возможность менять количество товара в корзине
  - Пользователь должен иметь возможность сбрасывать фильтр пердметов
  - Пользователь должен иметь возможность фильтовать товары по цене
  - Пользователь должен иметь возможность выбрать какое количество товара добавить в корзину
  - Фильтры по цене должны проверять, что цена ОТ больше чем ДО
  - Фильтры по цене должны проверять, что цена не может быть отрицательной
  - Пользователь должен иметь возможность отслеживать статус заказа
  - Пользователь должен иметь возможность отменить заказ или часть заказа
